### ISSUE TITLE
Removing yarn.lock and installing fresh deps results in hardhat circom not producing any output files

### ISSUE THREAD

**Issue by beauwilliams** [0xPARC/circom-starter#10]
I'm trying to figure out what is causing this.

After running circom:dev it ends at `hardhat-circom:info Everything went okay, circom safe +1ms`

But no files are generated, there are no errors either. It seems to be a dependency issue

**Comment by phated** [comment]
@beauwilliams Huge thanks for reporting this! I wouldn't have noticed it otherwise. Sorry for the month delay, but the latest commits should be working.

**Comment by beauwilliams** [comment]
Great work and no problem at all mate! I'll try it out now 👍 Thank you
